// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IhavenoideawhatIchangedthistime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IhavenoideawhatIchangedthistime));
        
        string IMigrationMetadata.Id
        {
            get { return "201710290132245_I have no idea what I changed this time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
